import {parseCourseReferenceCSV} from './core.mjs';
import {activeRecords,listPathways,savePathway,savePathways} from './storage.mjs';
import {DISCIPLINES,SUBDISCIPLINES,COURSE_LEVELS,INCLUDE_VALUES,aggregateObservedCourses,calculateCoverage,classificationIsFull,makeConfirmed} from './pathways.mjs';
const $=id=>document.getElementById(id), fmt=n=>new Intl.NumberFormat().format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const st={ref:new Map(),records:[],saved:new Map(),courses:[]};
const opts=(vals,cur)=>vals.map(v=>'<option value="'+esc(v)+'" '+(v===cur?'selected':'')+'>'+esc(v)+'</option>').join('');
const unresolved=c=>!classificationIsFull(c)||c.status!=='Administrator Confirmed';
function visible(){const q=$('search').value.trim().toLowerCase(),f=$('statusFilter').value;return st.courses.filter(x=>{const c=x.classification,h=[x.code,x.officialTitle,x.floridaDiscipline,x.gradeBand,...x.observedTitles,...x.schools,c.discipline,c.subdiscipline,c.pathway,c.courseLevel,c.include,c.status].join(' ').toLowerCase();return(!q||h.includes(q))&&(f==='all'||(f==='unresolved'&&unresolved(c))||(f==='confirmed'&&c.status==='Administrator Confirmed')||(f==='excluded'&&c.include==='No'));});}
function coverage(){const c=calculateCoverage(st.courses,st.records,st.saved),m=[['Observed course codes',c.courses.total],['Fully classified',c.courses.fully],['Partially classified',c.courses.partially],['Review needed',c.courses.review],['Excluded',c.courses.excluded],['Classified enrollments',c.enrollment.full],['Enrollments unresolved',c.enrollment.partial+c.enrollment.review],['Students fully classified',c.students.fully],['Students affected by review',c.students.unresolved]];$('coverageMetrics').innerHTML=m.map(x=>'<div class="metric"><span>'+esc(x[0])+'</span><strong>'+fmt(x[1])+'</strong></div>').join('');const d=c.enrollment.full+c.enrollment.partial+c.enrollment.review,p=d?(c.enrollment.full/d*100).toFixed(1):'0.0';$('coverageDetail').innerHTML='<strong>Enrollment pathway coverage:</strong> '+p+'% of included/awaiting-review records are fully classified. Certification does not require 100%, but unresolved classifications remain visible.';}
function render(){const list=visible();$('reviewSummary').textContent=fmt(list.length)+' courses shown · '+fmt(list.reduce((a,c)=>a+c.enrollmentCount,0))+' affected enrollment records';$('pathwayBody').innerHTML=list.length?list.map(x=>{const c=x.classification,subs=SUBDISCIPLINES[c.discipline]||['Review Needed'],schools=x.schools.length<=3?x.schools.join(', '):x.schools.slice(0,3).join(', ')+' +'+(x.schools.length-3)+' more',sc=c.status==='Administrator Confirmed'?'high':(c.status==='Review Needed'||c.include==='Review Needed'?'low':'medium');return '<tr data-code="'+esc(x.code)+'"><td><input class="row-select" type="checkbox" value="'+esc(x.code)+'"></td><td><strong>'+fmt(x.enrollmentCount)+'</strong> enrollments<br><span class="muted">'+fmt(x.studentCount)+' students · '+fmt(x.schools.length)+' schools</span></td><td><strong>'+esc(x.code)+' · '+esc(x.officialTitle)+'</strong><br><span class="muted">'+esc(x.floridaDiscipline)+' · '+esc(x.gradeBand)+'</span><br><span class="local-title">Observed: '+esc(x.observedTitles.join(' • ')||'No local title')+'</span><br><span class="muted">'+esc(schools)+'</span></td><td><select class="discipline">'+opts(DISCIPLINES,c.discipline)+'</select></td><td><select class="subdiscipline">'+opts(subs,c.subdiscipline)+'</select></td><td><input class="pathway" value="'+esc(c.pathway||'')+'"></td><td><select class="courseLevel">'+opts(COURSE_LEVELS,c.courseLevel||'Unknown')+'</select></td><td><select class="include">'+opts(INCLUDE_VALUES,c.include||'Review Needed')+'</select></td><td><span class="confidence '+sc+'">'+esc(c.status||'Review Needed')+'</span></td><td><textarea class="notes" rows="2">'+esc(c.notes||'')+'</textarea><br><button class="primary save-row">Save & confirm</button></td></tr>';}).join(''):'<tr><td colspan="10" class="muted">No courses match this view.</td></tr>';bind();coverage();}
function bind(){document.querySelectorAll('tr[data-code]').forEach(tr=>{const code=tr.dataset.code,d=tr.querySelector('.discipline'),s=tr.querySelector('.subdiscipline');d.onchange=()=>{const v=SUBDISCIPLINES[d.value]||['Review Needed'];s.innerHTML=opts(v,v.includes(s.value)?s.value:v[0]);};tr.querySelector('.save-row').onclick=async()=>{const x=st.courses.find(y=>y.code===code),prior=st.saved.get(code)||x.classification,next=makeConfirmed(prior,{code,include:tr.querySelector('.include').value,discipline:d.value,subdiscipline:s.value,pathway:tr.querySelector('.pathway').value.trim(),courseLevel:tr.querySelector('.courseLevel').value,notes:tr.querySelector('.notes').value.trim()});await savePathway(next);st.saved.set(code,next);rebuild();};});}
function rebuild(){st.courses=aggregateObservedCourses(st.records,st.ref,st.saved);render();}
function bulkSubs(){const d=$('bulkDiscipline').value;$('bulkSubdiscipline').innerHTML='<option value="">Subdiscipline unchanged</option>'+((SUBDISCIPLINES[d]||[]).map(v=>'<option>'+esc(v)+'</option>').join(''));}
function setupBulk(){$('bulkDiscipline').innerHTML='<option value="">Discipline unchanged</option>'+DISCIPLINES.map(v=>'<option>'+esc(v)+'</option>').join('');$('bulkPathway').innerHTML='<option value="">Pathway unchanged</option>'+['Band','Orchestra','Chorus','Guitar','Keyboard / Piano','Modern Band','Digital Music','General Music','Music Theory','Music Appreciation','Music','Visual Art','Theatre','Dance','Review Needed'].map(v=>'<option>'+v+'</option>').join('');$('bulkDiscipline').onchange=bulkSubs;}
$('search').oninput=render;$('statusFilter').onchange=render;$('selectAll').onchange=()=>document.querySelectorAll('.row-select').forEach(c=>c.checked=$('selectAll').checked);
$('bulkApply').onclick=async()=>{const codes=[...document.querySelectorAll('.row-select:checked')].map(c=>c.value),u={discipline:$('bulkDiscipline').value,subdiscipline:$('bulkSubdiscipline').value,pathway:$('bulkPathway').value,include:$('bulkInclude').value};if(!codes.length||!Object.values(u).some(Boolean)){ $('reviewSummary').textContent=!codes.length?'Select at least one course.':'Choose at least one bulk field.';return;}const arr=[];for(const code of codes){const x=st.courses.find(y=>y.code===code),prior=st.saved.get(code)||x.classification,p={};Object.entries(u).forEach(([k,v])=>{if(v)p[k]=v});if(p.discipline&&!p.subdiscipline){const v=SUBDISCIPLINES[p.discipline]||[];if(!v.includes(prior.subdiscipline))p.subdiscipline=v[0]||'Review Needed';}const next=makeConfirmed(prior,{...p,code});st.saved.set(code,next);arr.push(next);}await savePathways(arr);$('selectAll').checked=false;rebuild();};
$('exportBtn').onclick=()=>{const q=v=>'"'+String(v??'').replaceAll('"','""')+'"',cols=['Course Code','Official Florida Course Title','Florida Discipline','Grade Band','Observed SDOC Titles','Enrollment Count','Student Count','Schools Using Course','SDOC Discipline','Subdiscipline','Pathway','Course Level','Include in Arts Analytics','Classification Status','Administrator Notes'],lines=[cols.map(q).join(',')];st.courses.forEach(x=>{const c=st.saved.get(x.code)||x.classification;lines.push([x.code,x.officialTitle,x.floridaDiscipline,x.gradeBand,x.observedTitles.join(' | '),x.enrollmentCount,x.studentCount,x.schools.join(' | '),c.discipline,c.subdiscipline,c.pathway,c.courseLevel,c.include,c.status,c.notes].map(q).join(','));});const u=URL.createObjectURL(new Blob([lines.join('\r\n')],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='sdoc-arts-pathway-dictionary-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
setupBulk();
try{const [t,r,s]=await Promise.all([fetch('./data/florida-arts-courses.csv').then(x=>x.text()),activeRecords(),listPathways()]);st.ref=parseCourseReferenceCSV(t);st.records=r;st.saved=new Map(s.map(x=>[x.code,x]));rebuild();$('loadStatus').textContent=fmt(r.length)+' active enrollments · '+fmt(st.courses.length)+' observed course codes';if(!r.length)$('reviewSummary').textContent='No active enrollment records are available in this browser. Import and approve a dataset first.';}catch(e){$('loadStatus').textContent='Pathway Dictionary could not load.';$('reviewSummary').textContent=e.message||String(e);$('reviewSummary').className='status error';}